
language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t sebulibah/udagram-api-feed -f udagram-api-feed/ .
  - docker tag udagram-api-feed sebulibah/udagram-api-feed:latest
  - docker build -t sebulibah/udagram-api-user -f udagram-api-user/ .
  - docker tag udagram-api-user sebulibah/udagram-api-user:latest
  - docker build -t sebulibah/udagram-api-frontend -f udagram-api-frontend/ .
  - docker tag udagram-api-frontend sebulibah/udagram-api-frontend:latest
  - docker build -t sebulibah/udagram-reverse-proxy -f udagram-reverse-proxy/ .
  - docker tag udagram-reverse-proxy sebulibah/udagram-reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sebulibah/udagram-api-feed
  - docker push sebulibah/udagram-api-feed
  - docker push sebulibah/udagram-api-feed
  - docker push sebulibah/udagram-api-feed