
language: node_js
node_js:
  - 13
env:
  matrix:
    - NAME=udagram-api-feed
      DOCKER_BUILD=sebulibah/udagram-api-feed
      DOCKERFILE=udagram-api-feed
    - NAME=udagram-api-user 
      DOCKER_BUILD=sebulibah/udagram-api-user 
      DOCKERFILE=udagram-api-user
    - NAME=udagram-frontend
      DOCKER_BUILD=sebulibah/udagram-frontend
      DOCKERFILE=udagram-frontend
    - NAME=udagram-reverse-proxy
      DOCKER_BUILD=sebulibah/udagram-reverse-proxy
      DOCKERFILE=udagram-reverse-proxy

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t ${DOCKER_BUILD} -f ${DOCKERFILE}/Dockerfile .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${DOCKER_BUILD}
